"""Named navigation thresholds and scheduler settings."""

TARGET_CLOSE_DIST = 50.0
PASSED_TARGET_BEHIND_MIN_DEG = 90.0
PEER_APPROACH_DIST = 500.0
PEER_APPROACH_MARGIN_M = 200.0
DIST_EPS = 5.0
DIST_INC_MAX = 1
ALT_HYST = 3.0

MAX_CONFIRM_GATE_RESETS = 2
CONFIRM_REACQUIRE_ABORT_SEC = 2.5
TRACK_LOSS_GEO_HOLD_TIMEOUT_SEC = 180.0
TRACK_REACQUIRE_GATE_RADIUS_M = 30.0
CONFIRM_MAX_DWELL_SEC = 45.0
CONFIRM_DWELL_MARGIN_SEC = 5.0
TARGET_REACQUIRE_COOLDOWN_SEC = 10.0
GUIDED_ACCEPT_TIMEOUT_S = 5.0
# Retry at heartbeat scale until ArduPilot reports GUIDED. This is a fixed
# transport-safety cadence, not a simulation or tuning parameter.
GUIDED_REQUEST_RETRY_INTERVAL_S = 1.0
TERMINAL_RECORD_TIMEOUT_S = 5.0
CONFIRM_FRESH_DETECTION_MAX_AGE_S = 1.0
CONFIRM_REASK_MAX_ATTEMPTS = 2

# ArduPilot navigation scheduler frequency. Simulator speed changes only the
# wall cadence adapter, never source timestamps or decision-time values.
NAV_LOOP_RATE_HZ = 25.0
NAV_LOOP_PERIOD_S = 1.0 / NAV_LOOP_RATE_HZ


__all__ = [
    "ALT_HYST",
    "CONFIRM_DWELL_MARGIN_SEC",
    "CONFIRM_FRESH_DETECTION_MAX_AGE_S",
    "CONFIRM_MAX_DWELL_SEC",
    "CONFIRM_REACQUIRE_ABORT_SEC",
    "CONFIRM_REASK_MAX_ATTEMPTS",
    "DIST_EPS",
    "DIST_INC_MAX",
    "GUIDED_ACCEPT_TIMEOUT_S",
    "GUIDED_REQUEST_RETRY_INTERVAL_S",
    "MAX_CONFIRM_GATE_RESETS",
    "NAV_LOOP_PERIOD_S",
    "NAV_LOOP_RATE_HZ",
    "PASSED_TARGET_BEHIND_MIN_DEG",
    "PEER_APPROACH_DIST",
    "PEER_APPROACH_MARGIN_M",
    "TARGET_CLOSE_DIST",
    "TARGET_REACQUIRE_COOLDOWN_SEC",
    "TERMINAL_RECORD_TIMEOUT_S",
    "TRACK_LOSS_GEO_HOLD_TIMEOUT_SEC",
    "TRACK_REACQUIRE_GATE_RADIUS_M",
]
