#!/usr/bin/env python3
r"""
gen_codex_agents - generate .codex/agents/*.toml from .claude/agents/*.md.

`.claude/agents/*.md` is the SINGLE SOURCE OF TRUTH for agent definitions. The
Codex CLI reads its own `.codex/agents/*.toml` format, so the two sets used to be
maintained by hand and silently drifted apart (the TOML side missed PR #228 and
still pointed at a lowercase `agents.md` for months).

This script removes the second copy as a thing anyone edits. Edit the Markdown,
run the script, commit both. `tests/scripts/test_gen_codex_agents.py` fails the
suite if the two ever diverge again.

Mapping (Claude frontmatter -> Codex TOML):
    name:        -> name = "..."
    description: -> description = "..."
    body         -> developer_instructions = \"\"\"...\"\"\"

Claude-only keys (tools/model/permissionMode/maxTurns) have no Codex equivalent
and are dropped. Agents in CODEX_EXCLUDE get no TOML at all - they drive live
hardware or delete repo state, and were deliberately never given to Codex.

Line endings: the previous generator wrote CRLF text into a TOML *basic* string
and half-escaped it, leaving a literal `\r` before every real newline. TOML
parses `\r` as a carriage return, so every Codex agent prompt was full of stray
CRs. This script writes plain newlines and never emits an escape for them.

Usage:
    python scripts/gen_codex_agents.py            # regenerate .codex/agents/
    python scripts/gen_codex_agents.py --check    # exit 1 if regeneration differs
    python scripts/gen_codex_agents.py --list     # print the resolved agent set
"""
import argparse
import difflib
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / ".claude" / "agents"
OUT_DIR = REPO_ROOT / ".codex" / "agents"

# Agents intentionally NOT exposed to Codex. `janitor` deletes worktrees and
# branches; `live-tester` launches real SITL/GCS stacks. Adding either here is a
# capability decision, not a formatting one - do not "fix" the drift by removing
# them from this set.
CODEX_EXCLUDE = frozenset({"janitor", "live-tester"})

# Frontmatter keys that map into the TOML. Everything else is Claude-only.
REQUIRED_KEYS = ("name", "description")

FRONTMATTER_RE = re.compile(r"\A---\n(?P<meta>.*?)\n---\n(?P<body>.*)\Z", re.S)
BANNER = "# GENERATED by scripts/gen_codex_agents.py from .claude/agents/{stem}.md\n"
BANNER += "# Do not edit by hand - edit the Markdown source and re-run the script.\n"


class AgentParseError(ValueError):
    """Raised when a .md agent file is not shaped the way the generator needs."""


def parse_agent_md(path):
    """Return (frontmatter_dict, body_str) for one .claude/agents/*.md file.

    Reads with universal newlines so a CRLF checkout and an LF checkout parse
    identically. The frontmatter parser is deliberately dumb - these files use
    flat `key: value` lines only, and a real YAML dependency would be the sole
    reason to add one.
    """
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise AgentParseError(f"{path.name}: missing `---` YAML frontmatter block")

    meta = {}
    for line in match.group("meta").split("\n"):
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise AgentParseError(f"{path.name}: frontmatter line is not `key: value`: {line!r}")
        key, value = key.strip(), value.strip()
        # These are the ways real YAML would mean something this parser does not
        # implement. Raising beats emitting a plausible-looking but wrong value
        # into an agent prompt nobody re-reads.
        if key in meta:
            raise AgentParseError(f"{path.name}: duplicate frontmatter key `{key}`")
        if value in (">", "|", ">-", "|-"):
            raise AgentParseError(
                f"{path.name}: `{key}` uses a YAML block scalar; this parser only reads flat values"
            )
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            raise AgentParseError(
                f"{path.name}: `{key}` is YAML-quoted; write it unquoted, the quotes would be kept literally"
            )
        meta[key] = value

    for key in REQUIRED_KEYS:
        if not meta.get(key):
            raise AgentParseError(f"{path.name}: frontmatter is missing `{key}`")

    body = match.group("body").strip("\n")
    if not body:
        raise AgentParseError(f"{path.name}: body is empty")

    for key in REQUIRED_KEYS:
        reject_control_chars(meta[key], path, f"`{key}`")
    reject_control_chars(body, path, "body")
    return meta, body


def reject_control_chars(value, path, field):
    """Raise if `value` holds a character TOML cannot carry in a basic string.

    TOML allows tab and newline but no other C0 control, and no DEL. Without this
    the generator would happily write a .toml that `tomllib` refuses to read, and
    the failure would surface as an unreadable agent instead of a clear error.
    """
    for ch in value:
        if (ch < " " or ch == "\x7f") and ch not in "\t\n":
            raise AgentParseError(
                f"{path.name}: {field} contains control character {ch!r}; "
                "TOML basic strings cannot carry it"
            )


def escape_basic(value):
    """Escape a string for a single-line TOML basic string."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def escape_multiline(value):
    r"""Escape a string for a multi-line TOML basic string (\"\"\"...\"\"\").

    Only backslashes and quotes need handling. Newlines stay literal - the stray
    `\r` escapes in the hand-written TOML files are exactly the bug this avoids.

    Inside `\"\"\"...\"\"\"` up to two adjacent quotes are legal, so a quote only
    needs escaping when it would close the string early: the third quote of a run,
    or the last character of the body (which sits against the closing delimiter).

    This is one left-to-right pass on purpose. Escaping quote runs and then
    separately fixing up a trailing quote double-escapes a body ending in
    `\"\"\"` - the run pass already left a backslash there.
    """
    out = []
    run = 0  # consecutive unescaped quotes emitted so far
    last = len(value) - 1
    for i, ch in enumerate(value):
        if ch == "\\":
            out.append("\\\\")
            run = 0
        elif ch == '"':
            run += 1
            if run >= 3 or i == last:
                out.append('\\"')
                run = 0
            else:
                out.append('"')
        else:
            out.append(ch)
            run = 0
    return "".join(out)


def render_toml(meta, body, stem):
    """Render one agent as Codex TOML text with `\n` newlines."""
    return (
        BANNER.format(stem=stem)
        + f'name = "{escape_basic(meta["name"])}"\n'
        + f'description = "{escape_basic(meta["description"])}"\n'
        + f'developer_instructions = """\n{escape_multiline(body)}"""\n'
    )


def rel(path):
    """Repo-relative path for messages, falling back to the absolute path."""
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def collect(src_dir=None):
    """Return [(stem, toml_text)] for every agent Codex should get."""
    src_dir = SRC_DIR if src_dir is None else src_dir
    if not src_dir.is_dir():
        raise AgentParseError(f"agent source directory not found: {src_dir}")
    rendered = []
    for path in sorted(src_dir.glob("*.md")):
        if path.stem in CODEX_EXCLUDE:
            continue
        meta, body = parse_agent_md(path)
        rendered.append((path.stem, render_toml(meta, body, path.stem)))
    if not rendered:
        raise AgentParseError(f"no agent definitions found in {src_dir}")
    return rendered


def read_normalized(path):
    r"""Read a generated file back, collapsing CRLF to `\n` and nothing else.

    The repo has no .gitattributes and runs with core.autocrlf=true, so a Windows
    checkout has CRLF on disk and a Linux checkout has LF. Folding CRLF keeps
    --check meaningful on both without either side rewriting the other.

    `newline=""` matters: universal-newline mode would also fold a LONE CR into
    `\n`, so a file whose newlines had all been mangled to bare CRs would compare
    equal and pass the drift gate - while `tomllib` refuses to parse it. That is
    the exact class of corruption this generator exists to prevent, so lone CRs
    must survive the read and show up as a difference.
    """
    if not path.exists():
        return None
    # Path.read_text() only grew a newline= argument in 3.13; open() works everywhere.
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read().replace("\r\n", "\n")


def write(rendered, out_dir=None):
    """Write the rendered TOML files, returning the paths actually changed."""
    out_dir = OUT_DIR if out_dir is None else out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    changed = []
    for stem, text in rendered:
        path = out_dir / f"{stem}.toml"
        if read_normalized(path) != text:
            # newline=None translates \n to the platform ending, matching what
            # core.autocrlf checks out, so a fresh regen leaves the tree clean.
            path.write_text(text, encoding="utf-8", newline=None)
            changed.append(path)
    return changed


def check(rendered, out_dir=None):
    """Return a list of human-readable drift reports; empty means in sync."""
    out_dir = OUT_DIR if out_dir is None else out_dir
    problems = []
    expected = {f"{stem}.toml" for stem, _ in rendered}
    for stem, text in rendered:
        path = out_dir / f"{stem}.toml"
        current = read_normalized(path)
        if current is None:
            problems.append(f"{rel(path)}: MISSING")
            continue
        if current != text:
            diff = difflib.unified_diff(
                current.split("\n"), text.split("\n"),
                fromfile=f"{path.name} (on disk)", tofile=f"{path.name} (generated)",
                lineterm="",
            )
            problems.append("\n".join(diff))
    for path in sorted(out_dir.glob("*.toml")):
        if path.name not in expected:
            problems.append(f"{rel(path)}: STALE (no .md source, or excluded)")
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--check", action="store_true",
                        help="verify .codex/agents is in sync; exit 1 and print a diff if not")
    parser.add_argument("--list", action="store_true",
                        help="print the agent stems that would be generated, then exit")
    args = parser.parse_args(argv)

    rendered = collect()

    if args.list:
        for stem, _ in rendered:
            print(stem)
        return 0

    if args.check:
        problems = check(rendered)
        if problems:
            print("\n\n".join(problems))
            print(f"\n{len(problems)} file(s) out of sync. "
                  "Run: python scripts/gen_codex_agents.py", file=sys.stderr)
            return 1
        print(f"OK: {len(rendered)} Codex agent file(s) match .claude/agents/")
        return 0

    changed = write(rendered)
    for path in changed:
        print(f"wrote {rel(path)}")
    print(f"{len(changed)} changed, {len(rendered) - len(changed)} already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
